title = "Config for Colmi Client"

[device_config]
name = "R02_8B00"
address = "b82e1012-11b6-5639-aba5-24525e239b6e"

[device_config.features]
command_id = 47
supports_temperature = true
supports_plate = false
supports_menstruation = false
supports_custom_wallpaper = false
supports_blood_oxygen = false
supports_blood_pressure = false
supports_unknown_feature = false
supports_one_key_check = false
supports_weather = false
supports_wechat = false
supports_avatar = false
width = 0
height = 0
use_new_sleep_protocol = false
max_watch_faces = 0
supports_contacts = false
supports_lyrics = false
supports_album = false
supports_gps = false
supports_jeilei_music = false
supports_manual_heart_rate = false
supports_ecard = false
supports_location = false
supports_music = false
supports_ebook = false
supports_blood_sugar = false
max_contacts = 20
supports_blood_pressure_settings = true
supports_4g = false
supports_nav_picture = false
supports_pressure = false
supports_hrv = false
checksum = 35
